dbuser: 'braschan'
password: 'braschand'
host: 'localhost'
port: 5432
dbname: 'brand'
secret: 'askdjaksd2328173dasd'

smtpHost: 'smtp.hostnet.nl'
smtpPort: 587
smtpUser: 'info@resalewebsite.io'
smtpPassword: 'Ischin32!Ischin32!'
